services:
  miniconda:
    image: continuumio/anaconda3
    ports:
      - 8888:8888
    volumes:
      - ..:/workspace
    command: sh -c "
        conda install jupyter -y --quiet && \
        pip install minikanren && \
        pip install sympy && \
        mkdir -p /workspace && \
        jupyter notebook \
        --notebook-dir=/workspace --ip='*' --port=8888 --no-browser --allow-root
      "
